/* Copyright (C) YOOtheme GmbH, YOOtheme Proprietary Use License (http://www.yootheme.com/license) */

(function(j){var v=$widgetkit.support,w=[],m=function(){},l={width:"auto",height:"auto",index:0,autoplay:false,effect:"slide",interval:5E3,easing:"easeOutCirc",duration:300};m.prototype=j.extend(m.prototype,{name:"slideset",initialize:function(c){this.options=j.extend({},l,c);var a=this,e=this.element;this.sets=e.find("ul.set");this.navitems=e.find("ul.nav").children();this.current=this.sets[this.options.index]?this.options.index:0;this.busy=false;this.timer=null;this.hover=false;this.gwidth=this.options.width==
"auto"?e.width():this.options.width;this.navitems.each(function(c){j(this).bind("click",function(){a.stop().show(c)})});e.find(".next, .prev").bind("click",function(){a.stop()[j(this).hasClass("next")?"next":"previous"]()});"ontouchend"in document&&(e.bind("touchstart",function(c){function f(c){if(a){var d=c.originalEvent.touches?c.originalEvent.touches[0]:c;b={time:(new Date).getTime(),coords:[d.pageX,d.pageY]};Math.abs(a.coords[0]-b.coords[0])>10&&c.preventDefault()}}var g=c.originalEvent.touches?
c.originalEvent.touches[0]:c,a={time:(new Date).getTime(),coords:[g.pageX,g.pageY],origin:j(c.target)},b;e.bind("touchmove",f).one("touchend",function(){e.unbind("touchmove",f);a&&b&&b.time-a.time<1E3&&Math.abs(a.coords[0]-b.coords[0])>30&&Math.abs(a.coords[1]-b.coords[1])<75&&a.origin.trigger("swipe").trigger(a.coords[0]>b.coords[0]?"swipeleft":"swiperight");a=b=void 0})}),e.bind("swipeleft",function(){a.next()}).bind("swiperight",function(){a.previous()}));this.resize();j(window).bind("resize",
function(){a.resize()});this.navitems.eq(this.current).addClass("active");e.hover(function(){a.hover=true},function(){a.hover=false});this.options.autoplay&&this.start()},resize:function(){this.sets.css($widgetkit.css3({transform:""}));var c=this.element.find(".sets:first"),a=c.css({width:""}).width(),e=0,i=this.options.width=="auto"?this.element.width():this.options.width,f=this.options.height=="auto"?this.sets.eq(0).children().eq(0).outerHeight(true):this.options.height;this.sets.each(function(){var c=
j(this).show(),a=j(this).children();tmp=0;a.each(function(){var b=j(this);b.css("left",tmp).data("left",tmp);tmp+=b.width()});e=Math.max(e,tmp);c.css("width",tmp).css("margin-left","").css("margin","0 auto").data("width",tmp)});this.element.data("optimalwidth",e);i=this.options.width=="auto"?this.element.width():this.options.width;f=this.options.height=="auto"?this.sets.eq(0).children().eq(0).outerHeight(true):this.options.height;this.sets.css({height:f});c.css({height:f});this.element.data("optimalwidth")>
a&&(i=e,a=e/a,this.sets.css($widgetkit.css3({transform:"scale("+1/a+")"})),c.css("height",f/a));this.sets.each(function(){var c=j(this);c.data("margin-left",(i-c.data("width"))/2)});this.sets.hide().eq(this.current).show();this.gheight=f},next:function(){this.show(this.sets[this.current+1]?this.current+1:0)},previous:function(){this.show(this.current-1>-1?this.current-1:this.sets.length-1)},start:function(){if(!this.timer){var c=this;this.timer=setInterval(function(){!c.hover&&!c.busy&&c.next()},
this.options.interval);return this}},stop:function(){if(this.timer){clearInterval(this.timer);this.tmptimer&&clearTimeout(this.tmptimer);var c=this;this.tmptimer=setTimeout(function(){c.start();this.tmptimer=false},3E4);this.timer=false}return this},show:function(c){this.current==c||this.busy||(this.element.trigger("slideset-show",[this.current,c]),this[this[this.options.effect]?this.options.effect:"slide"](c),this.navitems.removeClass("active").eq(c).addClass("active"))},slide:function(c){var a=
c>this.current?"left":"right",e=this.sets.eq(c),i=this;this.busy=true;this.sets.eq(this.current).animate({"margin-left":(a=="left"?-1:1)*2*this.gwidth},{complete:function(){e.css("margin-left","auto").children().hide().css({left:(a=="left"?1:-1)*2*i.gwidth});e.show();i.sets.eq(i.current).hide();var f=e.children(),g=0;f.each(function(e){a=="right"&&(e=f.length-1-e);(function(b,c){setTimeout(function(){f.eq(b).show().animate({left:f.eq(b).data("left")},{complete:function(){if(a=="left"&&b==f.length-
1||a=="right"&&b==0)i.busy=false,i.current=c},duration:i.options.duration,easing:i.options.easing})},100*g)})(e,c);g+=1})}})},zoom:function(c){var a=this.sets.eq(c),e=0,i=this.sets.eq(this.current).children(),f=this;this.busy=true;this.sets.eq(this.current).children().animate(jQuery.support.opacity?{transform:"scale(0)",opacity:0}:{opacity:0},{complete:function(){e+=1;if(!(e!=-1&&e<i.length-1)){e=-1;var g=a.children().css(jQuery.support.opacity?{transform:"scale(0)",opacity:0}:{opacity:0}),j=0;f.sets.eq(f.current).hide();
a.show();g.each(function(b){g.eq(b).css({left:g.eq(b).data("left")}).show();(function(b,d){setTimeout(function(){g.eq(b).show().animate(jQuery.support.opacity?{transform:"scale(1)",opacity:1}:{opacity:1},{complete:function(){if(b==g.length-1)f.busy=false,f.current=d},duration:f.options.duration,easing:f.options.easing})},Math.round(f.options.duration/3)*j)})(b,c);j+=1})}},easing:"swing",duration:Math.round(f.options.duration/2)})},deck:function(c){if(!jQuery.support.opacity)return this.zoom(c);var a=
c>this.current?"left":"right",e=this.sets.eq(c),i=this.sets.eq(this.current).children(),f=this.sets.eq(c).children();i[c>this.current?"first":"last"]();f[c>this.current?"last":"first"]();var g=this;a=="right"&&i._reverse();a=="right"&&f._reverse();this.busy=true;i.each(function(a){var b=j(this);(function(b,d){setTimeout(function(){d.animate({transform:"scale(0)",opacity:0},{complete:function(){d.hide();b==i.length-1&&(g.sets.eq(g.current).hide(),f.css({transform:"scale(0)",opacity:0}),e.show(),f.each(function(b){var d=
j(this);(function(b,d){setTimeout(function(){d.animate({transform:"scale(1)",opacity:1},{complete:function(){if(b==f.length-1)i.show().each(function(b){i.eq(b).css({transform:"scale(1)",opacity:1,left:i.eq(b).data("left")})}),g.busy=false,g.current=c},duration:g.options.duration,easing:g.options.easing})},Math.round(g.options.duration/3)*b)})(b,d)}))},duration:g.options.duration,easing:g.options.easing})},Math.round(g.options.duration/3)*b)})(a,b)})},drops:function(c){if(!jQuery.support.opacity)return this.zoom(c);
var a=c>this.current?"left":"right",e=this.sets.eq(c),i=this.sets.eq(this.current).children().css($widgetkit.css3({transition:""})).css($widgetkit.css3({transform:"rotate(0deg)",top:0,opacity:1})),f=this.sets.eq(c).children().css($widgetkit.css3({transition:""}));i[c>this.current?"first":"last"]();f[c>this.current?"last":"first"]();var g=this;a=="right"&&i._reverse();a=="right"&&f._reverse();this.busy=true;i.each(function(a){var b=j(this);(function(b,d){setTimeout(function(){if(v.transition){d.css($widgetkit.css3({transition:"all "+
g.options.duration+"ms ease-out"}));if(b==i.length-1)d.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){g.sets.eq(g.current).hide();f.css($widgetkit.css3({top:g.gheight,opacity:0,transform:"rotate(15deg)"}));e.show();f.each(function(b){var d=j(this);(function(b,d){setTimeout(function(){d.css($widgetkit.css3({transition:"all "+g.options.duration+"ms ease-in"}));if(b==f.length-1)d.one("webkitTransitionEnd transitionend oTransitionEnd msTransitionEnd",function(){g.busy=
false;g.current=c});d.css($widgetkit.css3({opacity:1,top:0,transform:"rotate(0deg)"}))},Math.round(g.options.duration/3)*b)})(b,d)})});d.css($widgetkit.css3({opacity:0,top:g.gheight,transform:"rotate(15deg)"}))}else d.animate({opacity:0,top:g.gheight},{complete:function(){d.hide();b==i.length-1&&(g.sets.eq(g.current).hide(),f.css({top:g.gheight,opacity:0}),e.css("margin-left","").show(),f.each(function(b){var d=j(this);(function(b,d){setTimeout(function(){d.animate({opacity:1,top:0},{complete:function(){if(b==
f.length-1)i.show().each(function(b){i.eq(b).css({opacity:1,top:0})}),g.busy=false,g.current=c},duration:g.options.duration,easing:g.options.easing})},Math.round(g.options.duration/3)*b)})(b,d)}))},duration:g.options.duration,easing:g.options.easing})},20+Math.round(g.options.duration/3)*b)})(a,b)})}});if(!j.fn._reverse)j.fn._reverse=[].reverse;j.fn[m.prototype.name]=function(){var c=arguments,a=c[0]?c[0]:null;return this.each(function(){var e=j(this);if(m.prototype[a]&&e.data(m.prototype.name)&&
a!="initialize")e.data(m.prototype.name)[a].apply(e.data(m.prototype.name),Array.prototype.slice.call(c,1));else if(!a||j.isPlainObject(a)){var i=new m;i.element=e;w.push(i);m.prototype.initialize&&i.initialize.apply(i,c);e.data(m.prototype.name,i)}else j.error("Method "+a+" does not exist on jQuery."+m.prototype.name)})}})(jQuery);
(function(j){function v(b){for(var b=b.split(")"),c=j.trim,d=b.length-1,r,a,h,e=1,f=0,g=0,i=1,o,p,n,l=0,s=0;d--;){r=b[d].split("(");a=c(r[0]);h=r[1];o=r=p=n=0;switch(a){case "translateX":l+=parseInt(h,10);continue;case "translateY":s+=parseInt(h,10);continue;case "translate":h=h.split(",");l+=parseInt(h[0],10);s+=parseInt(h[1]||0,10);continue;case "rotate":h=m(h);o=Math.cos(h);r=Math.sin(h);p=-Math.sin(h);n=Math.cos(h);break;case "scaleX":o=h;n=1;break;case "scaleY":o=1;n=h;break;case "scale":h=h.split(",");
o=h[0];n=h.length>1?h[1]:h[0];break;case "skewX":o=n=1;p=Math.tan(m(h));break;case "skewY":o=n=1;r=Math.tan(m(h));break;case "skew":o=n=1;h=h.split(",");p=Math.tan(m(h[0]));r=Math.tan(m(h[1]||0));break;case "matrix":h=h.split(","),o=+h[0],r=+h[1],p=+h[2],n=+h[3],l+=parseInt(h[4],10),s+=parseInt(h[5],10)}a=e*o+f*p;f=e*r+f*n;o=g*o+i*p;i=g*r+i*n;e=a;g=o}return[e,f,g,i,l,s]}function w(b){var c,d,a,e=b[0],h=b[1],f=b[2],g=b[3];e*g-h*f?(c=Math.sqrt(e*e+h*h),e/=c,h/=c,a=e*f+h*g,f-=e*a,g-=h*a,d=Math.sqrt(f*
f+g*g),f/=d,g/=d,a/=d,e*g<h*f&&(e=-e,h=-h,a=-a,c=-c)):rotate=c=d=a=0;return{translate:[+b[4],+b[5]],rotate:Math.atan2(h,e),scale:[c,d],skew:[a,0]}}function m(b){return~b.indexOf("deg")?parseInt(b,10)*(Math.PI*2/360):~b.indexOf("grad")?parseInt(b,10)*(Math.PI/200):parseFloat(b)}for(var l=document.createElement("div"),l=l.style,c=["OTransform","msTransform","WebkitTransform","MozTransform","transform"],a=c.length,e,i,f,g,t=/Matrix([^)]*)/;a--;)c[a]in l&&(j.support.transform=e=c[a]);if(!e)j.support.matrixFilter=
i=l.filter==="";l=l=null;j.cssNumber.transform=true;e&&e!="transform"?(j.cssProps.transform=e,e=="MozTransform"?f={get:function(b,c){return c?j.css(b,e).split("px").join(""):b.style[e]},set:function(b,c){b.style[e]=/matrix[^)p]*\)/.test(c)?c.replace(/matrix((?:[^,]*,){4})([^,]*),([^)]*)/,"matrix$1$2px,$3px"):c}}:/^1\.[0-5](?:\.|$)/.test(j.fn.jquery)&&(f={get:function(b,c){return c?j.css(b,e.replace(/^ms/,"Ms")):b.style[e]}})):i&&(f={get:function(b,c){var d=c&&b.currentStyle?b.currentStyle:b.style,
a;d&&t.test(d.filter)?(a=RegExp.$1.split(","),a=[a[0].split("=")[1],a[2].split("=")[1],a[1].split("=")[1],a[3].split("=")[1]]):a=[1,0,0,1];a[4]=d?d.left:0;a[5]=d?d.top:0;return"matrix("+a+")"},set:function(b,c,d){var a=b.style,e,f,g;if(!d)a.zoom=1;c=v(c);if(!d||d.M)if(f=["Matrix(M11="+c[0],"M12="+c[2],"M21="+c[1],"M22="+c[3],"SizingMethod='auto expand'"].join(),g=(e=b.currentStyle)&&e.filter||a.filter||"",a.filter=t.test(g)?g.replace(t,f):g+" progid:DXImageTransform.Microsoft."+f+")",centerOrigin=
j.transform.centerOrigin)a[centerOrigin=="margin"?"marginLeft":"left"]=-(b.offsetWidth/2)+b.clientWidth/2+"px",a[centerOrigin=="margin"?"marginTop":"top"]=-(b.offsetHeight/2)+b.clientHeight/2+"px";if(!d||d.T)a.left=c[4]+"px",a.top=c[5]+"px"}});f&&(j.cssHooks.transform=f);g=f&&f.get||j.css;j.fx.step.transform=function(b){var c=b.elem,d=b.start,a=b.end,l,h=b.pos,x,y,z,A,o=false,p=false,n;x=y=z=A="";if(!d||typeof d==="string"){d||(d=g(c,e));if(i)c.style.zoom=1;l=a.split(d);if(l.length==2)a=l.join(""),
b.origin=d,d="none";d=="none"?d={translate:[0,0],rotate:0,scale:[1,1],skew:[0,0]}:(d=/\(([^,]*),([^,]*),([^,]*),([^,]*),([^,p]*)(?:px)?,([^)p]*)(?:px)?/.exec(d),d=w([d[1],d[2],d[3],d[4],d[5],d[6]]));b.start=d;if(~a.indexOf("matrix"))a=w(v(a));else{a=a.split(")");l=[0,0];for(var t=0,s=[1,1],u=[0,0],B=a.length-1,C=j.trim,k,q;B--;)k=a[B].split("("),q=C(k[0]),k=k[1],q=="translateX"?l[0]+=parseInt(k,10):q=="translateY"?l[1]+=parseInt(k,10):q=="translate"?(k=k.split(","),l[0]+=parseInt(k[0],10),l[1]+=parseInt(k[1]||
0,10)):q=="rotate"?t+=m(k):q=="scaleX"?s[0]*=k:q=="scaleY"?s[1]*=k:q=="scale"?(k=k.split(","),s[0]*=k[0],s[1]*=k.length>1?k[1]:k[0]):q=="skewX"?u[0]+=m(k):q=="skewY"?u[1]+=m(k):q=="skew"&&(k=k.split(","),u[0]+=m(k[0]),u[1]+=m(k[1]||"0"));a={translate:l,rotate:t,scale:s,skew:u}}b.end=a;for(n in d)(n=="rotate"?d[n]==a[n]:d[n][0]==a[n][0]&&d[n][1]==a[n][1])&&delete d[n]}d.translate&&(x=" translate("+(d.translate[0]+(a.translate[0]-d.translate[0])*h+0.5|0)+"px,"+(d.translate[1]+(a.translate[1]-d.translate[1])*
h+0.5|0)+"px)",o=true);d.rotate!=void 0&&(y=" rotate("+(d.rotate+(a.rotate-d.rotate)*h)+"rad)",p=true);d.scale&&(z=" scale("+(d.scale[0]+(a.scale[0]-d.scale[0])*h)+","+(d.scale[1]+(a.scale[1]-d.scale[1])*h)+")",p=true);d.skew&&(A=" skew("+(d.skew[0]+(a.skew[0]-d.skew[0])*h)+"rad,"+(d.skew[1]+(a.skew[1]-d.skew[1])*h)+"rad)",p=true);b=b.origin?b.origin+x+A+z+y:x+y+z+A;f&&f.set?f.set(c,b,{M:p,T:o}):c.style[e]=b};j.transform={centerOrigin:"margin"}})(jQuery);
